version: '3.9'
services:
  backend:
    build: ./src/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network

  frontend:
    build: ./src/frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge